In [1]:
import numpy as np

NumPy (Numerical Python), Python’da bilimsel ve sayısal hesaplamalar için kullanılan temel kütüphanedir. Çok boyutlu dizi (array) veri yapısını sağlar. Normal Python listelerine göre çok daha hızlı ve hafızada verimli çalışır.

# Array kavramı

**array**: Numpy içerisindeki aynı tipte verileri tutan liste benzeri yapıdır. Arraylar birden fazla boyutlu olabilir.

**np.array()** -> Başka veri tiplerinden numpy array oluşturulmasını sağlar.

In [2]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array([1, 2, 3, 4, 5])

print("Python listesi:", py_list)
print("NumPy array:", np_array)
print("Array tipi:", type(np_array))

Python listesi: [1, 2, 3, 4, 5]
NumPy array: [1 2 3 4 5]
Array tipi: <class 'numpy.ndarray'>


# Array Özellikleri

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) #2D array

**np.shape(arr) | arr.shape** -> Verilen array'in boyutlarını döndürür.    

In [4]:
print("Shape:", arr.shape)
print(np.shape(arr))

Shape: (2, 3)
(2, 3)


**np.ndim(arr) | arr.ndim** -> Verilen array'in boyut sayısını döndürür.

In [7]:
print("Boyut sayısı:", arr.ndim)
print(np.ndim(arr))

Boyut sayısı: 2
2


**np.size(arr) | arr.size** -> Verilen array'in eleman sayısını döndürür.  

In [8]:
print("Eleman sayısı:", arr.size)
print(np.size(arr))

Eleman sayısı: 6
6


**arr.itemsize**->Array'in her bir elemanının kaç byte kapladığını döndürür

In [10]:
print("Itemsize:", arr.itemsize)

Itemsize: 8


**arr.nbytes** -> Array'in toplam kaç byte olduğunu döndürür

In [11]:
print("Nbytes:", arr.nbytes)

Nbytes: 48


**arr.min()** -> array içerisindeki minimum değeri döndürür.        
**arr.max()** -> array içerisindeki maksimum değeri döndürür.       
**arr.argmin()** -> array içerisindeki minimum elemanın indeksini döndürür.     
**arr.argmax()** -> array içerisindeki maksimum elemanın indexini döndürür.

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) #2D array

In [14]:
print("Min:", arr.min())
print("Max:", arr.max())
print("Argmin:", arr.argmin())  # min’in index’i
print("Argmax:", arr.argmax())  # max’in index’i

Min: 1
Max: 6
Argmin: 0
Argmax: 5


**arr.cumsum()**->Array elemanlarının kümülatif toplamını alır.     
**arr.cumprod()** -> Array elemanlarının kümülatif çarpımını alır.

In [15]:
print("Cumsum:", arr.cumsum())  # Kümülatif toplam
print("Cumprod:", arr.cumprod()) # Kümülatif çarpım

Cumsum: [ 1  3  6 10 15 21]
Cumprod: [  1   2   6  24 120 720]


# Array Oluşturma

Python listeleri ve tuple'larından numpy array oluşturulabilir.

In [17]:
py_list = [1, 2, 3, 4, 5] #Tek boyutlu
arr1 = np.array(py_list)
print("Liste:", py_list)
print("NumPy array:", arr1)
print("Tipi:", type(arr1))

py_list_2d = [[1, 2, 3], [4, 5, 6]] #Çok boyutlu
arr2 = np.array(py_list_2d)
print("\nListe (2D):", py_list_2d)
print("NumPy array (2D):\n", arr2)

Liste: [1, 2, 3, 4, 5]
NumPy array: [1 2 3 4 5]
Tipi: <class 'numpy.ndarray'>

Liste (2D): [[1, 2, 3], [4, 5, 6]]
NumPy array (2D):
 [[1 2 3]
 [4 5 6]]


**np.zeros(shape)** -> Belirtilen shape'de tamamen sıfırlardan oluşan bir array oluşturur.

In [18]:
arr = np.zeros(3)
print(arr)
print(arr.shape)

arr = np.zeros((2, 3))
print(arr)
print(arr.shape)

[0. 0. 0.]
(3,)
[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


**np.ones(shape)** -> Belirtilen shape'de tamamen birlerden oluşan bir array oluşturur.

In [ ]:
arr = np.ones(5)
print(arr)
print(arr.shape)

arr = np.ones((3,3,3))
print(arr)
print(arr.shape)

**np.full(shape,x)** -> Verilen shape'de ve tamamen x ile doldurulmuş bir array oluşturur.

In [23]:
print(np.full((2, 2), 7))

[[7 7]
 [7 7]]


**np.arange(Başlangıç,Bitiş,Adım)**->Belirlenene aralıkta belirlenen adım sayısı ile beraber sayılar oluşturur. Float ile de iş yapar.

In [25]:
print(np.arange(0, 10, 2))

[0 2 4 6 8]


**np.linspace(Başlangıç,Bitiş,Aralık sayısı)**-> İki sayı arasında eşit aralıklar oluşturmak için kullanılır.

In [26]:
print(np.linspace(0, 1, 5)) 

[0.   0.25 0.5  0.75 1.  ]


**np.logspace(Başlangıç,Bitiş,Adet)** -> 10^başlangıç ve 10^bitiş arasını logaritmik olarak adet sayısına böler.

In [30]:
print(np.logspace(1, 3, 5)) # 10^1 ile 10^3 arasında logaritmik 5 sayı

[  10.           31.6227766   100.          316.22776602 1000.        ]


**np.diag(liste,k)**->Verilen liste ile diagonal matris oluşturur. k kaçıncı dioganal olacağını belirler.

In [38]:
print(np.diag([1,2,3,4],k=0))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


**np.identity(M)** -> MxM olacak şekilde birim matris üretir.

In [47]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**np.eye(M,N,k)** -> MxN olacak şekilde belirli bir diagonal boyunca 1 yerleştirir. k hangi dioganal olduğunu belirtir.

In [54]:
print(np.eye(6,5,0))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


**np.triu(arr)** -> Verilen arrayi üst üçgen matris haline getirir.     
**np.tril(arr)** -> Verilen arrayi alt üçgen matris haline getirir.

In [218]:
m = [[1,2,3],
     [4,5,6],
     [7,8,9]]
print(np.triu(m))  # Üst üçgen
print(np.tril(m))  # Alt üçgen

[[1 2 3]
 [0 5 6]
 [0 0 9]]
[[1 0 0]
 [4 5 0]
 [7 8 9]]


**np.empty(shape)** -> Verilen shape'de garbage value'lar ile array oluşturur.

In [222]:
print(np.empty((8,9)))   # Bellekteki rastgele değerlerle (hızlı, doldurmaz)

[[1.68836702e-315 0.00000000e+000 2.64325121e-321             nan
  4.94065646e-322 2.85915013e+242 3.93262085e-028 1.02123424e+277
  1.44014371e+228]
 [1.53487099e+025 1.54738352e-114 3.80974740e+180 6.35583534e+020
  1.02124015e+277 3.81187285e+180 2.82200878e+242 1.85474307e-004
  5.83153336e+180]
 [2.82216759e+242 1.85504109e-004 4.88706099e+199 6.47522208e+170
  9.25068518e+242 7.04386960e+199 1.94932375e+243 2.52022652e+180
  5.32070781e+233]
 [2.24089095e+089 9.90540978e+169 2.85809602e+242 4.77093018e+180
  1.67751539e+243 1.02874565e+113 1.23785117e+290 1.86128241e-004
  2.73649752e+113]
 [2.11268229e-110 3.90663404e+233 1.84841356e-004 1.93698154e-004
  9.75023779e+199 3.93270558e-028 3.17303269e+025 9.25079923e+242
  8.92846779e+252]
 [1.94466252e+243 2.11689915e-110 1.84841356e-004 4.06084130e+228
  1.53510896e+025 2.18110797e-114 3.45441458e+228 1.17075759e+214
  7.69469308e+170]
 [6.55737773e+179 6.99177865e+228 1.84841356e-004 6.21064460e+175
  6.99161584e+228 1.06209538

**np.tile(dizi,tekrar)** -> verilen diziyi tekrar adedince art arda tekrar eder.        
**np.repeat(dizi,tekrar)** -> verilen dizinin her bir elemanını tekrar adedince tekrar eder.

In [224]:
print(np.tile([1, 2, 3], 2))  # [1,2,3] dizisini 2 defa tekrar et
print(np.repeat([1, 2, 3], 3)) # Her elemanı 2 defa tekrar et

[1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]


# indexleme

In [65]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0:2])
print(arr[-1])

[10 20]
50


In [66]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(arr2d[0, 0])  # 1. satır, 1. sütun -> 1
print(arr2d[1, 2])  # 2. satır, 3. sütun -> 6
print(arr2d[-1, -1])# son satır, son sütun -> 9

1
6
9


In [69]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])   # 1. indexten 4’e kadar -> [20 30 40]
print(arr[:3])    # baştan 3. indexe kadar -> [10 20 30]
print(arr[::2])   # 2’şer atlayarak -> [10 30 50]

[20 30 40]
[10 20 30]
[10 30 50]


In [70]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(arr2d[0:2, 1:3]) # 1-2. satırlar ve 2-3. sütunlar

[[2 3]
 [5 6]]


In [73]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[[0, 2, 4]])  # 0., 2., 4. indexler -> [10 30 50]

[10 30 50]


# Veri Tipleri

**int** -> Tam sayılardır. Sonuna gelen sayı kaç bit tuttuğunu gösterir. (int8,int16,int32,int64)

In [82]:
print(np.array([-1, 2, 3], dtype=np.int8))

[-1  2  3]


**uint** -> İşaretsiz tam sayılardır. Yani sadece 0 ve pozitif değerleri tutarlar. (uint8, uint16, uint32, uint64)

In [78]:
print(np.array([1, 2, 3], dtype=np.uint8))

[1 2 3]


**float** -> Ondalıklı sayıları tutar. sonundaki bit değeri arttıkça depolama alanı ve hassasiyet artar. (float16, float32, float64)

In [80]:
print(np.array([1.5, 2, 3], dtype=np.float64))

[1.5 2.  3. ]


**bool** -> Mantıksal True ya da False tutar. 1 byte yer kaplar.

In [83]:
print(np.array([True, False, True, True], dtype=bool))

[ True False  True  True]


**object** -> Karışık veri tiplerini tutmak içindir. Performansı düşürdüğü için kullanımı fazla tavsiye edilmez.

In [84]:
print(np.array([1, "merhaba", 3.14, True], dtype=object))

[1 'merhaba' 3.14 True]


**datetime** -> Zaman verisini tutmak için kullanılır.

In [87]:
dates = np.array(['2025-08-15', '2025-08-16', '2025-08-17'], dtype='datetime64')
print(dates)

['2025-08-15' '2025-08-16' '2025-08-17']


**complex** -> complex sayıları tutmak için kullanılır.

In [88]:
z = np.array([1+2j, 3-4j, 5+0j], dtype=np.complex64)
print(z)

[1.+2.j 3.-4.j 5.+0.j]


**arr.dtype** -> Bir arrayin veri tipini öğrenmek için kullanılır.

In [89]:
print("Veri tipi:", arr.dtype)

Veri tipi: int64


Numpy içerisindeki bütün veri tipleri:

In [90]:
print("Dtype:", arr.dtype) 
print("Tüm dtype’lar:", np.sctypeDict.keys()) 

Dtype: int64
Tüm dtype’lar: dict_keys(['bool', 'float16', 'float32', 'float64', 'longdouble', 'complex64', 'complex128', 'clongdouble', 'bytes_', 'str_', 'void', 'object_', 'datetime64', 'timedelta64', 'int8', 'byte', 'uint8', 'ubyte', 'int16', 'short', 'uint16', 'ushort', 'int32', 'intc', 'uint32', 'uintc', 'int64', 'long', 'uint64', 'ulong', 'longlong', 'ulonglong', 'intp', 'uintp', 'double', 'cdouble', 'single', 'csingle', 'half', 'bool_', 'int_', 'uint', 'float', 'complex', 'object', 'bytes', 'a', 'int', 'str', 'unicode', 'float128', 'complex256'])


# Random

**np.random.rand(shape)** -> 0-1 arası olacak şekilde belirtilen shape'de array üretir.

In [105]:
print(np.random.rand(5,1)) 

[[0.69163464]
 [0.44253306]
 [0.45212619]
 [0.07029306]
 [0.9531884 ]]


**np.random.randint(Başlangıç,Bitiş,Shape)** -> Başlangıç ve bitiş değerleri arasında belirtilen shape'de rastgele array oluşturur. Bitiş dahil değildir. 

In [113]:
print(np.random.randint(1, 10, (2,2)))

[[9 2]
 [4 3]]


**np.random.randn(Shape)** -> Normal (Gaussian) dağılımdan (ortalama=0, std=1) rastgele sayılar üretir.

In [117]:
print(np.random.randn(2, 3))

[[-0.48262864 -0.57969139  0.51858904]
 [ 0.38323884  0.01895136 -0.80447496]]


**np.random.normal(Ortalama,Standart Sapma,Shape)** -> Belirli bir ortalamaya ve standart sapmaya sahip rastgele çıktılar üretir.

In [122]:
print(np.random.normal(0, 1, 5))    # Ortalama=0, std=1, 5 sayı
print(np.random.normal(100, 10, (2, 3)))  # Ortalama=100, std=10, 2x3 matris

[ 0.97808894 -0.09228166  0.04493757 -0.37998905 -0.98216506]
[[102.53870562 104.24935616 104.93828085]
 [107.79527782 104.65029066 115.48394714]]


**np.random.choice(arr,sayı,tekrar_durumu)** -> Bir diziden (array,liste,..) rastgele eleman seçmek için kullanılır. 

In [141]:
arr = [10, 20, 30, 40, 50]
print(np.random.choice(arr))          # Tek seçim
print(np.random.choice(arr, 3))       # 3 eleman seç
print(np.random.choice(arr, 5, replace=False)) # Tekrarsız seçim

20
[10 30 20]
[30 40 10 20 50]


**np.random.shuffle(arr)** -> arrayin elamanlarını rastgele karıştırır. in_place işlem yapar yani orijinal array üzerinde değişiklik yapılır, yeni bir kopya oluşturulmaz.

In [154]:
arr = [10, 20, 30, 40, 50]
np.random.shuffle(arr)
print(arr)

[50, 10, 40, 20, 30]


**np.random.seed(seed)**-> Aynı rastgele sonuçları üretmek için kullanılır (Reproducibility).

In [160]:
np.random.seed(42)
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]


# inf-nan kavramları

**inf** -> Çok büyük sayıları ifade eder. Genelde 0'a çok yakın sayılara bölme ile oluşur. Belirli bir bit sayısı ile ifade edilemediği için inf ile ifade edilir.      
**nan** -> (Not a Number) gerçek bir sayıya karşılık gelmez. 0/0 gibi tanımsız işlemler sonucu oluşur.

In [165]:
# Örnek array
arr = np.array([1, 2+3j, np.inf, np.nan, 5.0])

print("Is complex:", np.iscomplex(arr))   # Kompleks sayı mı?
print("Is real:", np.isreal(arr))         # Reel sayı mı?
print("Is finite:", np.isfinite(arr))     # Sonlu mu? (inf, nan hariç)
print("Is nan:", np.isnan(arr))           # NaN mı? (Not a Number)

Is complex: [False  True False False False]
Is real: [ True False  True  True  True]
Is finite: [ True  True False False  True]
Is nan: [False False False  True False]


In [169]:
print(np.nan == np.nan) #nan hiçbir şeye eşit değildir kendine bile

False


# Aritmetik işlemler

**element-wise** -> Bir arraydeki Her bir indexteki elemanın diğer array içerisinde aynı indexteki eleman ile işleme tabi tutulmasıdır. İşleme tabi tutulan arraylerin her biri aynı shape'de olmalıdır. Sonuçta oluşan array yine aynı shape'de olur.

In [173]:
a = np.array([-1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([-1, -2, 3])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a % b)
print(a ** b)
print(-a)
print(np.negative(a))
print(np.abs(c))

[3 7 9]
[-5 -3 -3]
[-4 10 18]
[-0.25  0.4   0.5 ]
[-1  0  0]
[3 2 3]
[  1  32 729]
[ 1 -2 -3]
[ 1 -2 -3]
[1 2 3]


In [175]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.min(a))
print(np.max(a))
print(np.std(a))
print(np.sqrt(a))

45
5.0
5.0
1
9
2.581988897471611
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


**axis** -> axis kavramı işlemin hangi boyutta yapılacağını belirtir. 2 Boyutlu bir array için:     
0 → satırlar boyunca (dikey)        
1 → sütunlar boyunca (yatay)        
Axis belirtilmezse bütün elemanlar üzerinde işlemler yapılır ve sonuç tek bir scalar olur.

In [176]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(np.sum(a, axis=0))  # Sütunları toplamak (axis=0)
print(np.sum(a, axis=1))  # Satırları toplamak (axis=1)

[5 7 9]
[ 6 15]


3 boyutlu ve daha derin array'ler için axis kavramı benzer mantıkta çalışır: En dıştaki katman axis=0 olmak üzere derinlik boyunca içeriye doğru axis artar.

**out** parametresi ile sonuç başka bir değişkene yazdırılabilir.

In [177]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.empty(3)
np.add(a, b, out=c)
print(c)  # [5. 7. 9.]

[5. 7. 9.]


Ardışık elemanlar arasındaki işlemler için de fonksiyonlar var.

In [179]:
a = np.array([1, 2, 3, 4])
print(np.cumsum(a))  # kümülatif toplam
print(np.cumprod(a)) # kümülatif çarpım
print(np.diff(a))    # ardışık fark

[ 1  3  6 10]
[ 1  2  6 24]
[1 1 1]


# Array şekil işlemleri

**reshape()** ile yeniden şekillendirme mümkündür. Yeni boyutların çarpımı eleman sayısını vermelidir. Bir boyutun **-1** verilmesi o boyutun otomatik doldurulacağı anlamına gelir.

In [183]:
b = np.arange(12)
print(b.shape)
print(b)
c = b.reshape(3, 4)
print(c)

(12,)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [188]:
b = np.arange(12)
print(b.shape)
print(b)
c = b.reshape(3, -1)
print(c)

(12,)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**newaxis** ile yeni boş bir eksen eklenebilir.

In [190]:
x = np.array([1, 2, 3])
print(x.shape)
y = x[:, np.newaxis]  # (3,) → (3,1)
print(y.shape)
print(y)

(3,)
(3, 1)
[[1]
 [2]
 [3]]


**flatten** ile bütün elemanlar düzleştirilebilir. Bu işlemden sonra bütün elemanlar tek bir listenin elemanıymış gibi olur.

In [193]:
b = np.arange(12).reshape(3,4)
print(b)
z = b.flatten()  #Düzleştirme
print(z.shape)   #
print(z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(12,)
[ 0  1  2  3  4  5  6  7  8  9 10 11]


**squeeze** -> Boyutu bir olan eksenleri kaldırır. (Fazla parantezleri)

In [196]:
a = np.array([[[1], [2], [3]]])
print("Orijinal shape:", a.shape)
b = a.squeeze()  # boyutu 1 olan ekseni kaldır
print("Squeezed shape:", b.shape)
print(b)

Orijinal shape: (1, 3, 1)
Squeezed shape: (3,)
[1 2 3]


**stack** -> Farklı arraylerin birleştirilmesini sağlar.

In [200]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print(np.vstack((a,b,c)))  # dikey
print(np.hstack((a,b,c)))  # yatay

print(np.dstack((a,b,c))) #Derinlik boyunca

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]]


In [203]:
c = np.array([[1,2],[3,4]])
d = np.array([[5,6],[7,8]])
print(c.shape)
v2 = np.vstack((c, d))
print("\nvstack 2D:\n", v2)
print("vstack 2D shape:", v2.shape)  # (4,2)

s2 = np.stack((c, d), axis=0) #Yeni bir Boyut ekleyerek birleştirir.
print("\nstack axis=0 2D:\n", s2)
print("stack axis=0 2D shape:", s2.shape)  # (2,2,2)

(2, 2)

vstack 2D:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
vstack 2D shape: (4, 2)

stack axis=0 2D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
stack axis=0 2D shape: (2, 2, 2)


**concatenate**->daha esnek birleştirme imkanı sunar (axis parametresi)

In [207]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.concatenate((a,b), axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


**split**->Arrayi eşit parçalara bölmeyi sağlar.

In [208]:
a = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9]
parts = np.array_split(a, 3)
for i, p in enumerate(parts):
    print(f"Part {i}:", p)

Part 0: [0 1 2 3]
Part 1: [4 5 6]
Part 2: [7 8 9]


In [213]:
b = np.arange(16).reshape(4,4)
print("Original array:\n", b)

# Satırlar boyunca böl (dikey)
rows_split = np.vsplit(b, 2)
print("\nVsplit:")
for part in rows_split:
    print(part)

# Sütunlar boyunca böl (yatay)
cols_split = np.hsplit(b, 2)
print("\nHsplit:")
for part in cols_split:
    print(part)

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Vsplit:
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]

Hsplit:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [2]:
c = np.arange(24).reshape(2,3,4)
print(c)
# Derinlik boyunca böl
depth_split = np.dsplit(c, 4)  # axis=2'yi (En son axis) böler
for i, part in enumerate(depth_split):
    print(f"\nDepth part {i}:\n", part)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Depth part 0:
 [[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]

Depth part 1:
 [[[ 1]
  [ 5]
  [ 9]]

 [[13]
  [17]
  [21]]]

Depth part 2:
 [[[ 2]
  [ 6]
  [10]]

 [[14]
  [18]
  [22]]]

Depth part 3:
 [[[ 3]
  [ 7]
  [11]]

 [[15]
  [19]
  [23]]]


# Lineer Cebir fonksiyonları

In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])

**Matrix çarpımı** ->

In [5]:
print("Dot product:\n", np.dot(A, B))   # matris çarpımı

Dot product:
 [[ 4  6]
 [10 12]]


In [6]:
print("Matmul:\n", np.matmul(A, B))     # aynı işlev

Matmul:
 [[ 4  6]
 [10 12]]


In [7]:
print("Kısayol @:\n", A @ B)

Kısayol @:
 [[ 4  6]
 [10 12]]


**Cross Product**

In [8]:
A = np.array([1, 2, 3])
B = np.array([2, 0, 5])

In [9]:
np.cross(A,B)

array([10,  1, -4])

**Determinant**->

In [10]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])

In [12]:
print("Determinant:", np.linalg.det(A))

Determinant: -2.0000000000000004


**inverse** ->

In [13]:
invA = np.linalg.inv(A)
print("A^-1:\n", invA)

A^-1:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [14]:
np.linalg.pinv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

**Transpose** ->

In [15]:
print("Transpoz:\n", A.T)

Transpoz:
 [[1 3]
 [2 4]]


In [16]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

**Trace** ->

In [18]:
A

array([[1, 2],
       [3, 4]])

In [17]:
print("Trace:", np.trace(A))   # köşegen toplamı

Trace: 5


**Rank**->

In [21]:
print("Rank:", np.linalg.matrix_rank(A))

Rank: 2


**eigenvalues/eigenvectors**

In [22]:
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


**singular value decomposition**

In [23]:
U, S, Vt = np.linalg.svd(A)
print("U:\n", U)
print("S (singular values):", S)
print("Vt:\n", Vt)

U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
S (singular values): [5.4649857  0.36596619]
Vt:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


**norm**

In [26]:
v = np.array([3, 4])
print(np.linalg.norm(v,ord=2))

5.0


**Lineer çözüm**

In [28]:
A = np.array([[2, 1], [1, 3]])
b = np.array([8, 13])
x = np.linalg.solve(A, b)
print("Çözüm x:", x)

Çözüm x: [2.2 3.6]


**En küçük kareler**

In [30]:
np.linalg.lstsq(A, b)

(array([2.2, 3.6]),
 array([], dtype=float64),
 np.int32(2),
 array([3.61803399, 1.38196601]))

# Broadcasting

eğer işlem yapılan arrayler aynı shape'de değilse numpy derinliği az olan array'i elemanları tekrar ederek genişletir.      
[1,2,3] shape (3,) → broadcast → (1,3) → her satır için kopyalanır → shape (2,3)        

In [42]:
a = np.array([[1,2,3],
              [4,5,6]])  # shape: (2,3)
b = np.array([10,20,30])  # shape: (3,)

c = a + b
print(c)

[[11 22 33]
 [14 25 36]]


In [44]:
row = np.array([[1],[2]])  # shape: (2,1)
col = np.array([10,20,30]) # shape: (3,)

# 1 1 1     10 20 30
# 2 2 2     10 20 30
result = row + col  # row ve col broadcasting
print(result)

[[11 21 31]
 [12 22 32]]


In [49]:
a = np.array([1,2,3])
b = np.array([[1],[2],[3]])
print(a-b)
print("*"*25)
print(a-b.flatten())

[[ 0  1  2]
 [-1  0  1]
 [-2 -1  0]]
*************************
[0 0 0]


# Masking-Filter

In [51]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
mask = arr > 20
print("Mask:", mask)
filtered = arr[mask]
print("Filtrelenmiş array:", filtered)

Mask: [False False False  True  True  True  True]
Filtrelenmiş array: [25 30 35 40]


In [53]:
print("20'den büyükler:", arr[arr > 20])

20'den büyükler: [25 30 35 40]


In [54]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

mask = mat > 5
print("Mask:\n", mask)
filtered = mat[mask]

Mask:
 [[False False False]
 [False False  True]
 [ True  True  True]]


In [56]:
print(arr[(arr > 15) & (arr < 35)])

[20 25 30]


In [58]:
arr = np.arange(10)
print(arr[(arr > 2) & (arr < 7)])
print(arr[(arr % 2 == 0) | (arr > 7)])
print(arr[~(arr > 5)])

[3 4 5 6]
[0 2 4 6 8 9]
[0 1 2 3 4 5]


In [59]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr[arr>5] = 1
print(arr)

[0 1 2 3 4 5 1 1 1 1]


**np.where(koşul,sağlandığı durum,sağlanmadığı durum)** -> Bir koşulun array'de sağlandığı ve sağlanmadığı yerler için işlem yapmayı sağlar.

In [61]:
arr = np.array([10, 20, 30, 40, 50])
result = np.where(arr > 30, 1, 0)
print(result)

[0 0 0 1 1]


# Array kopyalama

**shallow copy** -> Memory içerisinde başka bir yere kopyalanmaz. Birinde yapılan değişiklik diğerini etkiler.      
**deep copy** -> Memory içerisinde farklı bir yere kopyası oluşturulur.

In [62]:
a = np.array([1, 2, 3])
b = a 

b[0] = 100
print(a)

[100   2   3]


In [63]:
a = np.array([1, 2, 3])
b = a.view() #Shallow copy

b[1] = 200
print(a)

[  1 200   3]


In [64]:
a = np.array([1, 2, 3])
b = a.copy()  # deep copy

b[2] = 300
print(a)
print(b)

[1 2 3]
[  1   2 300]


# Array Kaydetme/yükleme

Tek bir array kaydetme

In [66]:
a = np.array([1, 2, 3, 4, 5])


np.save("my_array.npy", a)


b = np.load("my_array.npy")
print(b)

[1 2 3 4 5]


Birden çok array kaydetme

In [67]:
x = np.array([1, 2, 3])
y = np.array([[1, 2], [3, 4]])

np.savez("my_arrays.npz", arr1=x, arr2=y)

# Yükleme
data = np.load("my_arrays.npz")
print(data["arr1"])
print(data["arr2"])
                   

[1 2 3]
[[1 2]
 [3 4]]


text formatında kaydetme

In [68]:
np.savetxt("my_array.txt", a, delimiter=",", fmt="%d")
b = np.loadtxt("my_array.txt", delimiter=",")
print(b)

[1. 2. 3. 4. 5.]
